@url = https://8080-amber-constrictor-z86no4yt.ws-us20.gitpod.io
###
GET {{url}}/filmes

###

POST https://8080-amber-constrictor-z86no4yt.ws-us20.gitpod.io/filmes
Content-Content-Type: application/json

{
    "titulo" : "Exemplo"
}

###
PUT https://8080-amber-constrictor-z86no4yt.ws-us20.gitpod.io/filmes/5
Content-Content-Type: application/json

{
    "titulo" : "Ghostbusters"
}

###
DELETE https://8080-amber-constrictor-z86no4yt.ws-us20.gitpod.io/filmes
Content-Content-Type: application/json

{
    "id" : 5
}